Добавил webpack, ts и PostCss
ZurichProgectGroup/ZurichGameProject pull request #1
Opened 2020-12-17 18:41 UTC by dorvic

2020-12-17 18:51 UTC, mpgm commented on webpack.config.js
> +module.exports = {
Мб стоит сразу добавить алиасы для папок, чтобы не использовать относительные пути при импортах?

2020-12-17 18:57 UTC, mpgm commented on package.json
> +  "scripts": {
Наверное нужно еще на build добавить скрипт

2020-12-17 19:01 UTC, mpgm commented on webpack.config.js
> +const path = require("path");
В этом файле то двойные кавычки, то одиночные, я бы убрал из игнора линта его

2020-12-17 19:02 UTC, mpgm requested changes
Думаю стоит еще добавить stylelint

2020-12-18 06:13 UTC, elkabelaya commented on .npmrc
> +engine-strict=true
давайте заюзаем еще save-exact = true, чтобы при любой установке зависимостей в package.json записывалась точная версия

2020-12-18 06:13 UTC, elkabelaya commented on package.json
> +    "@typescript-eslint/eslint-plugin": "^4.10.0",
давайте без ^, чтобы не удариться больно об какой-нибудь минор

2020-12-18 06:13 UTC, elkabelaya commented on package.json
> +    "eslint-plugin-react-hooks": "^4.2.0",
мб, для css тоже прикрутим линтер?

2020-12-18 09:20 UTC, dorvic commented on webpack.config.js
> +const path = require("path");
Добавил в игнор потому что typescript плагин для линта ругается(

2020-12-18 15:50 UTC, mpgm approved these changes

2020-12-19 18:09 UTC, elkabelaya approved these changes

2020-12-20 11:52 UTC, Jarith commented on .eslintrc.js
> +        "no-param-reassign": "off",
Давайте не будем отключать. Переписывание входных параметров - плохая практика, можно сильно стрельнуть в ногу

2020-12-20 11:52 UTC, Jarith commented on .gitignore
> +.idea
Лучше взять готовый файл, например [отсюда](https://github.com/github/gitignore/blob/master/Node.gitignore)

2020-12-20 11:52 UTC, Jarith commented on .eslintignore
> +webpack.config.js
Конфиги не стоит игнорить

2020-12-20 11:52 UTC, Jarith commented on postcss.config.js
> +            require("postcss-import"),
Из-за игнора конфигов пропустили двойные кавычки вместо одинарных

2020-12-20 17:41 UTC, merged